spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/topo
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 30000
      pool-name: Hikari-auth
  data:
    redis:
      host: 127.0.0.1 # Redis服务器地址
      database: 10 # Redis数据库索引（默认为0）
      port: 6379 # Redis服务器连接端口
      password: geoscene123 # Redis服务器连接密码（默认为空）
      timeout: 3000ms # 连接超时时间（毫秒）
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 0


minio:
  endpoint: http://127.0.0.1:9001 #Minio服务所在地址
  accessKey: minioadmin #访问的key
  secretKey: 11335577 #访问的秘钥
  volumePath: /mnt/nfs #minio映射容器内部路径

knife4j:
  enable: false
  setting:
    language: zh_cn