
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/ase
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 30000
      pool-name: Hikari-admin
  data:
    redis:
      host: 127.0.0.1
      database: 10
      port: 6379
      password: geoscene123
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 200
          max-wait: -1ms
          max-idle: 10
          min-idle: 0

minio:
  endpoint: http://127.0.0.1:9000 #minio address
  accessKey: minioadmin #access key
  secretKey: minioadmin #access password
  volumePath: /mnt/nfs

knife4j:
  enable: false
  setting:
    language: zh_cn